version: '3'
services:
  frontend:
    build:
      context: ./Bet.PI
    container_name: betpi_frontend
    ports:
      - "3000:3000"
    networks:
      - betpi-network

networks:
  betpi-network:
    name: betPI
    external: true
